// <auto-generated />
using System;
using FiyiRequirements.Areas.BasicCore.Entities.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiyiRequirements.Migrations
{
    [DbContext(typeof(EFCoreContext))]
    [Migration("20240306121900_CLS2")]
    partial class CLS2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiyiRequirements.Areas.BasicCore.Entities.Failure", b =>
                {
                    b.Property<int>("FailureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FailureId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmergencyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("FailureId");

                    b.ToTable("Failure");
                });

            modelBuilder.Entity("FiyiRequirements.Areas.BasicCore.Entities.Parameter", b =>
                {
                    b.Property<int>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParameterId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime2");

                    b.Property<byte>("IsPrivate")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("ParameterId");

                    b.ToTable("Parameter");
                });

            modelBuilder.Entity("FiyiRequirements.Areas.CMSCore.Entities.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime");

                    b.Property<string>("IconURLPath")
                        .HasColumnType("varchar(8000)");

                    b.Property<int>("MenuFatherId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("URLPath")
                        .HasColumnType("varchar(8000)");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("MenuId");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8420),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8421),
                            IconURLPath = "",
                            MenuFatherId = 0,
                            Name = "BasicCore",
                            Order = 100,
                            URLPath = "",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 2,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8437),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8438),
                            IconURLPath = "",
                            MenuFatherId = 1,
                            Name = "Failure",
                            Order = 0,
                            URLPath = "/BasicCore/FailurePage",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 3,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8452),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8453),
                            IconURLPath = "",
                            MenuFatherId = 1,
                            Name = "Parameter",
                            Order = 0,
                            URLPath = "/BasicCore/ParameterPage",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 4,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8466),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8466),
                            IconURLPath = "",
                            MenuFatherId = 0,
                            Name = "BasicCulture",
                            Order = 200,
                            URLPath = "",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 5,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8480),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8481),
                            IconURLPath = "",
                            MenuFatherId = 4,
                            Name = "City",
                            Order = 0,
                            URLPath = "/BasicCulture/CityPage",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 6,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8494),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8495),
                            IconURLPath = "",
                            MenuFatherId = 4,
                            Name = "State",
                            Order = 0,
                            URLPath = "/BasicCulture/StatePage",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 7,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8509),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8509),
                            IconURLPath = "",
                            MenuFatherId = 4,
                            Name = "Country",
                            Order = 0,
                            URLPath = "/BasicCulture/CountryPage",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 8,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8522),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8523),
                            IconURLPath = "",
                            MenuFatherId = 4,
                            Name = "Planet",
                            Order = 0,
                            URLPath = "/BasicCulture/PlanetPage",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 9,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8536),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8537),
                            IconURLPath = "",
                            MenuFatherId = 4,
                            Name = "Sex",
                            Order = 0,
                            URLPath = "/BasicCulture/SexPage",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 10,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8551),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8552),
                            IconURLPath = "",
                            MenuFatherId = 0,
                            Name = "CMSCore",
                            Order = 300,
                            URLPath = "",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 11,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8564),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8565),
                            IconURLPath = "",
                            MenuFatherId = 10,
                            Name = "User",
                            Order = 0,
                            URLPath = "/CMSCore/UserPage",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 12,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8578),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8579),
                            IconURLPath = "",
                            MenuFatherId = 10,
                            Name = "Role",
                            Order = 0,
                            URLPath = "/CMSCore/RolePage",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 13,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8592),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8593),
                            IconURLPath = "",
                            MenuFatherId = 10,
                            Name = "Menu",
                            Order = 0,
                            URLPath = "/CMSCore/MenuPage",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 14,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8606),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8606),
                            IconURLPath = "",
                            MenuFatherId = 10,
                            Name = "Permission",
                            Order = 0,
                            URLPath = "/CMSCore/Permission",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 15,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8663),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8663),
                            IconURLPath = "",
                            MenuFatherId = 0,
                            Name = "FiyiRequirements",
                            Order = 0,
                            URLPath = "",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 16,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8681),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8682),
                            IconURLPath = "",
                            MenuFatherId = 15,
                            Name = "BlogPost",
                            Order = 0,
                            URLPath = "/FiyiRequirements/BlogPostPage",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 17,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8695),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8696),
                            IconURLPath = "",
                            MenuFatherId = 15,
                            Name = "Perfil",
                            Order = 0,
                            URLPath = "/FiyiRequirements/UserProfilePage",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 18,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8710),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8711),
                            IconURLPath = "",
                            MenuFatherId = 15,
                            Name = "Agenda",
                            Order = 0,
                            URLPath = "/FiyiRequirements/AgendaPage",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 19,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8724),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8724),
                            IconURLPath = "",
                            MenuFatherId = 15,
                            Name = "CarouselTemasDeInteres",
                            Order = 0,
                            URLPath = "/FiyiRequirements/CarouselTemasDeInteresPage",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 20,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8738),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8739),
                            IconURLPath = "",
                            MenuFatherId = 15,
                            Name = "MarketplaceServices",
                            Order = 0,
                            URLPath = "/FiyiRequirements/MarketplacePostServicePage",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            MenuId = 21,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8753),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8753),
                            IconURLPath = "",
                            MenuFatherId = 15,
                            Name = "Estadisticas",
                            Order = 0,
                            URLPath = "/Estadisticas",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        });
                });

            modelBuilder.Entity("FiyiRequirements.Areas.CMSCore.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8366),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8367),
                            Name = "Root",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8388),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8389),
                            Name = "Administrator",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8403),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8404),
                            Name = "Client",
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        });
                });

            modelBuilder.Entity("FiyiRequirements.Areas.CMSCore.Entities.RoleMenu", b =>
                {
                    b.Property<int>("RoleMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleMenuId"));

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RoleMenuId");

                    b.ToTable("RoleMenu");

                    b.HasData(
                        new
                        {
                            RoleMenuId = 1,
                            MenuId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            RoleMenuId = 2,
                            MenuId = 14,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("FiyiRequirements.Areas.CMSCore.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(380)");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(8000)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8203),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8217),
                            Email = "novillo.matias1@gmail.com",
                            Password = "Pq5FM4q7dDtlZBGcn0w8P0XjnEPDlTCcLUY5/bWVcuVJ4/kXRyHp62hPgry0R/ur+kEspHc+HK6XqqvA8OLXLw==",
                            RoleId = 1,
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            UserId = 2,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8248),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8249),
                            Email = "kalebem83@gmail.com",
                            Password = "Pq5FM4q7dDtlZBGcn0w8P0XjnEPDlTCcLUY5/bWVcuVJ4/kXRyHp62hPgry0R/ur+kEspHc+HK6XqqvA8OLXLw==",
                            RoleId = 2,
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            UserId = 3,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8266),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8267),
                            Email = "carlos.e.gariglio@gmail.com",
                            Password = "Pq5FM4q7dDtlZBGcn0w8P0XjnEPDlTCcLUY5/bWVcuVJ4/kXRyHp62hPgry0R/ur+kEspHc+HK6XqqvA8OLXLw==",
                            RoleId = 2,
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            UserId = 4,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8282),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8283),
                            Email = "martinlermer@hotmail.com",
                            Password = "Pq5FM4q7dDtlZBGcn0w8P0XjnEPDlTCcLUY5/bWVcuVJ4/kXRyHp62hPgry0R/ur+kEspHc+HK6XqqvA8OLXLw==",
                            RoleId = 2,
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            UserId = 5,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8298),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8299),
                            Email = "paolalocucion@yahoo.com.ar",
                            Password = "Pq5FM4q7dDtlZBGcn0w8P0XjnEPDlTCcLUY5/bWVcuVJ4/kXRyHp62hPgry0R/ur+kEspHc+HK6XqqvA8OLXLw==",
                            RoleId = 2,
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        },
                        new
                        {
                            UserId = 6,
                            Active = (byte)1,
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8315),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8315),
                            Email = "sinapsiscom@gmail.com",
                            Password = "Pq5FM4q7dDtlZBGcn0w8P0XjnEPDlTCcLUY5/bWVcuVJ4/kXRyHp62hPgry0R/ur+kEspHc+HK6XqqvA8OLXLw==",
                            RoleId = 2,
                            UserCreationId = 1,
                            UserLastModificationId = 1
                        });
                });

            modelBuilder.Entity("FiyiRequirements.Areas.FiyiRequirements.Entities.Agenda", b =>
                {
                    b.Property<int>("AgendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgendaId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AddressEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeOfEvent")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPatrocinador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubEventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("AgendaId");

                    b.ToTable("Agenda");
                });

            modelBuilder.Entity("FiyiRequirements.Areas.FiyiRequirements.Entities.BlogPost", b =>
                {
                    b.Property<int>("BlogPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogPostId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("MainTopic")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("NumberOfComments")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLikes")
                        .HasColumnType("int");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("BlogPostId");

                    b.ToTable("BlogPost");
                });

            modelBuilder.Entity("FiyiRequirements.Areas.FiyiRequirements.Entities.CarouselTemasDeInteres", b =>
                {
                    b.Property<int>("CarouselTemasDeInteresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarouselTemasDeInteresId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime");

                    b.Property<string>("ImageSlide1")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("ImageSlide2")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("ImageSlide3")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("LinkSlide1")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("LinkSlide2")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("LinkSlide3")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("CarouselTemasDeInteresId");

                    b.ToTable("CarouselTemasDeInteres");
                });

            modelBuilder.Entity("FiyiRequirements.Areas.FiyiRequirements.Entities.EstadisticaPaginasMasVisitadas", b =>
                {
                    b.Property<int>("EstadisticaPaginasMasVisitadasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadisticaPaginasMasVisitadasId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("EstadisticaPaginasMasVisitadasId");

                    b.ToTable("EstadisticaPaginasMasVisitadas");
                });

            modelBuilder.Entity("FiyiRequirements.Areas.FiyiRequirements.Entities.EstadisticaPostsMasVisitados", b =>
                {
                    b.Property<int>("EstadisticaPostsMasVisitadosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadisticaPostsMasVisitadosId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<int>("BlogPostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("EstadisticaPostsMasVisitadosId");

                    b.ToTable("EstadisticaPostsMasVisitados");
                });

            modelBuilder.Entity("FiyiRequirements.Areas.FiyiRequirements.Entities.EstadisticaServiciosMasVisitados", b =>
                {
                    b.Property<int>("EstadisticaServiciosMasVisitadosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadisticaServiciosMasVisitadosId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime");

                    b.Property<int>("MarketPlacePostServiceId")
                        .HasColumnType("int");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("EstadisticaServiciosMasVisitadosId");

                    b.ToTable("EstadisticaServiciosMasVisitados");
                });

            modelBuilder.Entity("FiyiRequirements.Areas.FiyiRequirements.Entities.MarketPlacePostService", b =>
                {
                    b.Property<int>("MarketPlacePostServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarketPlacePostServiceId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<string>("CUIT")
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime");

                    b.Property<string>("DomicilioComercial")
                        .HasColumnType("text");

                    b.Property<string>("DomicilioParticular")
                        .HasColumnType("text");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("LinkDelServicio")
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("LinkFacebook")
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("LinkInstagram")
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("Mail")
                        .HasColumnType("varchar(400)");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("varchar(800)");

                    b.Property<int>("NumberOfComments")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLikes")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfVisits")
                        .HasColumnType("int");

                    b.Property<int>("PointOfServiceNegative")
                        .HasColumnType("int");

                    b.Property<int>("PointOfServicePositive")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<string>("Referido1Barrio")
                        .HasColumnType("text");

                    b.Property<string>("Referido1Celular")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Referido1Mail")
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Referido2Barrio")
                        .HasColumnType("text");

                    b.Property<string>("Referido2Celular")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Referido2Mail")
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Referido3Barrio")
                        .HasColumnType("text");

                    b.Property<string>("Referido3Celular")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Referido3Mail")
                        .HasColumnType("varchar(400)");

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("MarketPlacePostServiceId");

                    b.ToTable("MarketPlacePostService");
                });

            modelBuilder.Entity("FiyiRequirements.Areas.FiyiRequirements.Entities.MarketPlacePostServiceComments", b =>
                {
                    b.Property<int>("MarketPlacePostServiceCommentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarketPlacePostServiceCommentsId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime");

                    b.Property<int>("MarketPlacePostServiceId")
                        .HasColumnType("int");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("MarketPlacePostServiceCommentsId");

                    b.ToTable("MarketPlacePostServiceComments");
                });

            modelBuilder.Entity("FiyiRequirements.Areas.FiyiRequirements.Entities.MarketPlacePostServiceMainCategory", b =>
                {
                    b.Property<int>("MarketPlacePostServiceMainCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarketPlacePostServiceMainCategoryId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime");

                    b.Property<string>("MainCategoryName")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("MarketPlacePostServiceMainCategoryId");

                    b.ToTable("MarketPlacePostServiceMainCategory");
                });

            modelBuilder.Entity("FiyiRequirements.Areas.FiyiRequirements.Entities.MarketPlacePostServiceMainZone", b =>
                {
                    b.Property<int>("MarketPlacePostServiceMainZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarketPlacePostServiceMainZoneId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime");

                    b.Property<string>("MainZoneName")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("MarketPlacePostServiceMainZoneId");

                    b.ToTable("MarketPlacePostServiceMainZone");
                });

            modelBuilder.Entity("FiyiRequirements.Areas.FiyiRequirements.Entities.MarketPlacePostServiceSubCategory", b =>
                {
                    b.Property<int>("MarketPlacePostServiceSubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarketPlacePostServiceSubCategoryId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("MarketPlacePostServiceSubCategoryId");

                    b.ToTable("MarketPlacePostServiceSubCategory");
                });

            modelBuilder.Entity("FiyiRequirements.Areas.FiyiRequirements.Entities.MarketPlacePostServiceSubZone", b =>
                {
                    b.Property<int>("MarketPlacePostServiceSubZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarketPlacePostServiceSubZoneId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime");

                    b.Property<string>("SubZoneName")
                        .IsRequired()
                        .HasColumnType("varchar(8000)");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("MarketPlacePostServiceSubZoneId");

                    b.ToTable("MarketPlacePostServiceSubZone");
                });

            modelBuilder.Entity("FiyiRequirements.Areas.FiyiRequirements.Entities.PostThumbsUpAndDown", b =>
                {
                    b.Property<int>("PostThumbsUpAndDownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostThumbsUpAndDownId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime");

                    b.Property<int>("MarketplacePostServiceId")
                        .HasColumnType("int");

                    b.Property<int>("ThumbsUpOrDown")
                        .HasColumnType("int");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.HasKey("PostThumbsUpAndDownId");

                    b.ToTable("PostThumbsUpAndDown");
                });

            modelBuilder.Entity("FiyiRequirements.Areas.FiyiRequirements.Entities.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserProfileId"));

                    b.Property<byte>("Active")
                        .HasColumnType("tinyint");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("BusinessName")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(800)");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTimeLastModification")
                        .HasColumnType("datetime");

                    b.Property<string>("FacebookURL")
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("FullName")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("InstagramURL")
                        .HasColumnType("varchar(8000)");

                    b.Property<byte>("IsSubscriptedToMensualNews")
                        .HasColumnType("tinyint");

                    b.Property<string>("JobTitle")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MainZone")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PointProfileCompletion")
                        .HasColumnType("int");

                    b.Property<int>("PointTrustService")
                        .HasColumnType("int");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("ProfileInformation")
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<int>("UserCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserLastModificationId")
                        .HasColumnType("int");

                    b.Property<string>("Zone")
                        .HasColumnType("varchar(500)");

                    b.HasKey("UserProfileId");

                    b.ToTable("UserProfile");

                    b.HasData(
                        new
                        {
                            UserProfileId = 1,
                            Active = (byte)1,
                            Address = "Natania 19. Manzana 126. Casa 1",
                            BirthDate = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8339),
                            City = "Cordoba Capital",
                            DateTimeCreation = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8336),
                            DateTimeLastModification = new DateTime(2024, 3, 6, 9, 19, 0, 30, DateTimeKind.Local).AddTicks(8337),
                            FullName = "Matias Alejandro Novillo",
                            IsSubscriptedToMensualNews = (byte)1,
                            JobTitle = "Desarrollador web",
                            PhoneNumber = "+543512329541",
                            PointProfileCompletion = 15,
                            PointTrustService = 50,
                            ProfileImage = "Uploads/FiyiRequirements/UserProfile/1.png",
                            ProfileInformation = "Hola, soy Matias",
                            Sex = 1,
                            UserCreationId = 1,
                            UserId = 1,
                            UserLastModificationId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
